### ISSUE TITLE
Seems like the reviews are out, do you plan to release the code?

### ISSUE THREAD

**Issue by kumuji** [HarborYuan/PolyphonicFormer#1]
@HarborYuan , hi!

CVPR reviews are out and I hope you are doing great. Do you plan to release the code?

Best,
Alexey

**Comment by lxtGH** [comment]
@kumuji Hi! Thanks for your attention. We will release the both train/eval/demo code and models depend on the ECCV reviews. 

The code will be released before the ECCV conference.
