### ISSUE TITLE
About Code Release

### ISSUE THREAD

**Issue by Harry-Zhi** [HarborYuan/PolyphonicFormer#2]
Hi @lxtGH ,

Congrats on your paper accpeted by ECCV2022.

I am quite interested in your paper, especially on how to fuse queries of two frames within Transformer. 

I am wondering when you could plan to release the network as well as train/eval codes? 

Thank you very much.

**Comment by HarborYuan** [comment]
Hi @Harry-Zhi ,

Thanks for your interest,

We will release our codes before the ECCV 22 conference.

**Comment by Harry-Zhi** [comment]
> Hi @Harry-Zhi ,
> 
> Thanks for your interest,
> 
> We will release our codes before the ECCV 22 conference.

Hi,
As the conference is coming very soon.

Could it be possible for you to  release the codes recently?

Very looking forwards to your codes.
