### ISSUE TITLE
Request the Dataloader and evaluation for SemKittiDVPS

### ISSUE THREAD

**Issue by QingCheng24** [HarborYuan/PolyphonicFormer#8]
Hello, I have a question about the instance ID in SemKittiDVPS dataset.

The instance GT image is read with and merged into a set for the `val` set
instance = cv2.imread(instance_path, cv2.IMREAD_ANYDEPTH)

It looks like that the instances are labelled incrementally but the total number of ids is 354 instead of 396 which is indicated by the final instance id. So I'm a little bit confused about the meaning of the ids. Could you please provide the  Dataloader and evaluation for SemKittiDVPS?

**Comment by HarborYuan** [comment]
Hi @QingCheng24 ,

Thanks for your question.

In the SemKITTI-DVPS dataset, each instance will be assigned a unique ID in the whole sequence. That means some instances may disappear while the camera is moving. You may not use the max instance id as the count number of instances.

**Comment by QingCheng24** [comment]
Thank you for the reply. 

I'm also interested in the trained models on SemKitti-DVPS dataset as it is more close to our use case. Do you have any plan to release them as well?
